name: ReActions
api-version: '1.16'
main: me.fromgate.reactions.ReActionsPlugin
version: ${project.version}-b${buildNumber}
website: http://fromgate.me
author: fromgate, fromgate@gmail.com
softdepend: [Vault,WorldGuard,WorldEdit,ProtocolLib,PlaceholderAPI]
description: Simplest scripting engine for Bukkit
commands:
  reactions:
    aliases: [ra,rea,react]
    description: Main command of ReActions
    usage: /<command> help
  exec:
    aliases: [run]
    description: Execute EXEC-activator
    usage: /<command> <ActivatorId> [player:<PlayerSelector>] [delay:<Time>]