version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8u181-jdk
    steps:
    - checkout
    - run: mvn clean package
    - store_artifacts:
        path: target/ReActions.jar
        destination: ReActions.jar