name: ReActions
description: '${project.parent.description}'
api-version: '1.19'
main: fun.reactions.ReActionsPlugin
version: '${project.version}${build-suffix}'
website: https://github.com/imDaniX/ReActions
authors:
  - fromgate
  - MaxDikiy
  - imDaniX
softdepend: [ProtocolLib]
commands:
  reactions:
    aliases: [ra,rea,react]
    description: Main command of ReActions
    usage: /<command> help
  exec:
    aliases: [run]
    description: Execute EXEC-activator
    usage: /<command> <ActivatorId> [player:<PlayerSelector>] [delay:<Time>]
