name: ReActions
description: '${project.parent.description}'
api-version: '1.21'
main: fun.reactions.ReActionsPlugin
version: '${project.version}${build-suffix}'
website: https://github.com/GlowingInk/ReActions
authors:
  - fromgate
  - MaxDikiy
  - imDaniX
softdepend: [ProtocolLib]

