name: ReActions
api-version: '1.16'
main: me.fromgate.reactions.ReActionsPlugin
version: '${project.version}.${sub-version}-${build-version}'
website: https://github.com/imDaniX/ReActions
authors:
  - fromgate fromgate@gmail.com
  - MaxDikiy
  - imDaniX
softdepend: [Vault,WorldGuard,WorldEdit,ProtocolLib,PlaceholderAPI]
description: '${project.description}'
commands:
  reactions:
    aliases: [ra,rea,react]
    description: Main command of ReActions
    usage: /<command> help
  exec:
    aliases: [run]
    description: Execute EXEC-activator
    usage: /<command> <ActivatorId> [player:<PlayerSelector>] [delay:<Time>]
